"""fix unique constraint naming

Revision ID: 35472029c32a
Revises: 
Create Date: 2025-12-24 11:48:37.716114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35472029c32a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_awh',
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=True),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_awh_dedup')
    )
    with op.batch_alter_table('fact_awh', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_awh_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_awh_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_awh_vehicle'), ['vehicle'], unique=False)

    op.create_table('fact_ha',
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=True),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_ha_dedup')
    )
    with op.batch_alter_table('fact_ha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_ha_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_ha_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_ha_vehicle'), ['vehicle'], unique=False)

    op.create_table('fact_hb',
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=True),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_hb_dedup')
    )
    with op.batch_alter_table('fact_hb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_hb_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_hb_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_hb_vehicle'), ['vehicle'], unique=False)

    op.create_table('fact_idle',
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=True),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_idle_dedup')
    )
    with op.batch_alter_table('fact_idle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_idle_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_idle_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_idle_vehicle'), ['vehicle'], unique=False)

    op.create_table('fact_speeding',
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=True),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_speeding_dedup')
    )
    with op.batch_alter_table('fact_speeding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_speeding_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_speeding_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_speeding_vehicle'), ['vehicle'], unique=False)

    op.create_table('fact_trip',
    sa.Column('stop_time', sa.Time(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('distance_gps', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('trip_idle_flag', sa.String(length=50), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=True),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_trip_dedup')
    )
    with op.batch_alter_table('fact_trip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_trip_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_trip_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_trip_vehicle'), ['vehicle'], unique=False)

    op.create_table('fact_wh',
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=True),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_wh_dedup')
    )
    with op.batch_alter_table('fact_wh', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_wh_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_wh_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_wh_vehicle'), ['vehicle'], unique=False)

    op.create_table('fact_wu',
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=True),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_wu_dedup')
    )
    with op.batch_alter_table('fact_wu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_wu_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_wu_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_wu_vehicle'), ['vehicle'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_wu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_wu_vehicle'))
        batch_op.drop_index(batch_op.f('ix_fact_wu_event_date'))
        batch_op.drop_index(batch_op.f('ix_fact_wu_app_id'))

    op.drop_table('fact_wu')
    with op.batch_alter_table('fact_wh', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_wh_vehicle'))
        batch_op.drop_index(batch_op.f('ix_fact_wh_event_date'))
        batch_op.drop_index(batch_op.f('ix_fact_wh_app_id'))

    op.drop_table('fact_wh')
    with op.batch_alter_table('fact_trip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_trip_vehicle'))
        batch_op.drop_index(batch_op.f('ix_fact_trip_event_date'))
        batch_op.drop_index(batch_op.f('ix_fact_trip_app_id'))

    op.drop_table('fact_trip')
    with op.batch_alter_table('fact_speeding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_speeding_vehicle'))
        batch_op.drop_index(batch_op.f('ix_fact_speeding_event_date'))
        batch_op.drop_index(batch_op.f('ix_fact_speeding_app_id'))

    op.drop_table('fact_speeding')
    with op.batch_alter_table('fact_idle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_idle_vehicle'))
        batch_op.drop_index(batch_op.f('ix_fact_idle_event_date'))
        batch_op.drop_index(batch_op.f('ix_fact_idle_app_id'))

    op.drop_table('fact_idle')
    with op.batch_alter_table('fact_hb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_hb_vehicle'))
        batch_op.drop_index(batch_op.f('ix_fact_hb_event_date'))
        batch_op.drop_index(batch_op.f('ix_fact_hb_app_id'))

    op.drop_table('fact_hb')
    with op.batch_alter_table('fact_ha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_ha_vehicle'))
        batch_op.drop_index(batch_op.f('ix_fact_ha_event_date'))
        batch_op.drop_index(batch_op.f('ix_fact_ha_app_id'))

    op.drop_table('fact_ha')
    with op.batch_alter_table('fact_awh', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_awh_vehicle'))
        batch_op.drop_index(batch_op.f('ix_fact_awh_event_date'))
        batch_op.drop_index(batch_op.f('ix_fact_awh_app_id'))

    op.drop_table('fact_awh')
    # ### end Alembic commands ###
