"""add location and sync schema

Revision ID: aadb8a4ce097
Revises: 35472029c32a
Create Date: 2025-12-24 12:44:12.400020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aadb8a4ce097'
down_revision = '35472029c32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_speeding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=500), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('vehicle',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('driver',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_fact_speeding_app_id'))
        batch_op.drop_index(batch_op.f('ix_fact_speeding_event_date'))
        batch_op.drop_index(batch_op.f('ix_fact_speeding_vehicle'))
        batch_op.drop_constraint(batch_op.f('uq_fact_speeding_dedup'), type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('tag_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_speeding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_fact_speeding_dedup'), ['app_id', 'event_date', 'start_time', 'vehicle'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_fact_speeding_vehicle'), ['vehicle'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_speeding_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_speeding_app_id'), ['app_id'], unique=False)
        batch_op.alter_column('driver',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('vehicle',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('location')

    # ### end Alembic commands ###
