"""standardize location and duration across all facts

Revision ID: bd0a7bfebd07
Revises: aadb8a4ce097
Create Date: 2025-12-24 13:05:34.610383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0a7bfebd07'
down_revision = 'aadb8a4ce097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_awh', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))

    with op.batch_alter_table('fact_ha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))

    with op.batch_alter_table('fact_hb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))

    with op.batch_alter_table('fact_idle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))

    with op.batch_alter_table('fact_speeding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('vehicle',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('driver',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_fact_speeding_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_speeding_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_speeding_vehicle'), ['vehicle'], unique=False)
        batch_op.create_unique_constraint('uq_fact_speeding_dedup', ['app_id', 'event_date', 'start_time', 'vehicle'])

    with op.batch_alter_table('fact_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))
        batch_op.drop_column('address')

    with op.batch_alter_table('fact_wh', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))

    with op.batch_alter_table('fact_wu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_wu', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('fact_wh', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('fact_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('location')

    with op.batch_alter_table('fact_speeding', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fact_speeding_dedup', type_='unique')
        batch_op.drop_index(batch_op.f('ix_fact_speeding_vehicle'))
        batch_op.drop_index(batch_op.f('ix_fact_speeding_event_date'))
        batch_op.drop_index(batch_op.f('ix_fact_speeding_app_id'))
        batch_op.alter_column('location',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('driver',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('vehicle',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('tag_id')

    with op.batch_alter_table('fact_idle', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('fact_hb', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('fact_ha', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('fact_awh', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
