"""initial schema

Revision ID: f7435c702372
Revises: 
Create Date: 2026-03-10 16:01:20.511045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7435c702372'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('report_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id')
    )
    op.create_table('fact_awh',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_awh')
    )
    op.create_table('fact_ha',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_ha')
    )
    op.create_table('fact_idle',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_idle')
    )
    op.create_table('fact_speeding',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('speed_limit', sa.Float(), nullable=True),
    sa.Column('over_limit', sa.Float(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_speeding')
    )
    op.create_table('fact_trip',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('stop_time', sa.DateTime(), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('distance_gps', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('event_state', sa.String(length=50), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_trip')
    )
    op.create_table('fact_wu',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('violation_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_date', 'start_time', 'vehicle', name='uq_fact_wu')
    )
    op.create_table('job_execution',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('render',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.String(length=50), nullable=False),
    sa.Column('period_end', sa.String(length=50), nullable=False),
    sa.Column('tag_id', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('report_id', sa.String(length=100), nullable=False),
    sa.Column('render_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('render_id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=100), nullable=False),
    sa.Column('report_id', sa.String(length=100), nullable=False),
    sa.Column('render_id', sa.String(length=100), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.Column('gdrive_file_id', sa.String(length=128), nullable=True),
    sa.Column('gdrive_link', sa.String(length=1024), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('render_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('render')
    op.drop_table('job_execution')
    op.drop_table('fact_wu')
    op.drop_table('fact_trip')
    op.drop_table('fact_speeding')
    op.drop_table('fact_idle')
    op.drop_table('fact_ha')
    op.drop_table('fact_awh')
    op.drop_table('customer_configs')
    # ### end Alembic commands ###
